CATEGORIES = [
    "Vendor Payment",
    "Taxes/GST",
    "Client Inflow",
    "Salary",
    "EMI",
    "Rent",
    "Bills",
    "Professional Fees",
    "Logistics",
    "Subscription",
    "Travel",
    "Food",
    "Groceries",
    "Fuel",
    "Shopping",
    "Entertainment",
    "Healthcare",
    "Education",
    "Investment",
    "Insurance",
    "Transfer",
    "ATM/Cash",
    "Other",
]

INDIAN_BANKS = [
    "HDFC Bank",
    "ICICI Bank",
    "State Bank of India",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Punjab National Bank",
    "Canara Bank",
    "Bank of Baroda",
    "Union Bank of India",
    "Yes Bank",
    "IDFC First Bank",
    "IndusInd Bank",
    "Federal Bank",
    "Bank of India",
    "Indian Bank",
]
